name: AndroidCiMacOs

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  buildTest:
    name: Build SDK and HelloCardboard for Android
    runs-on: macos-10.15
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0
          submodules: 'true'
      - name: Install JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11
      - name: Build
        run: ./gradlew build
